/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSmartGuard: typeof import('./src/components/AppSmartGuard.vue')['default']
    BasePagination: typeof import('./src/components/BasePagination.vue')['default']
    BaseScrollbar: typeof import('./src/components/BaseScrollbar.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    InspectConfirmBox: typeof import('./src/components/InspectConfirmBox.vue')['default']
    InspectDateFilter: typeof import('./src/components/InspectDateFilter.vue')['default']
    InspectTable: typeof import('./src/components/InspectTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
