/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooterInside: typeof import('./src/components/AppFooterInside.vue')['default']
    AppFooterOutside: typeof import('./src/components/AppFooterOutside.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeaderLevel2: typeof import('./src/components/AppHeaderLevel2.vue')['default']
    AppIFramer: typeof import('./src/components/AppIFramer.vue')['default']
    AppSmartGuard: typeof import('./src/components/AppSmartGuard.vue')['default']
    BasePagination: typeof import('./src/components/BasePagination.vue')['default']
    BaseScrollbar: typeof import('./src/components/BaseScrollbar.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    InspectConfirmBox: typeof import('./src/components/InspectConfirmBox.vue')['default']
    InspectFilter: typeof import('./src/components/InspectFilter.vue')['default']
    InspectTable: typeof import('./src/components/InspectTable.vue')['default']
    MonitorVideoBoxFull: typeof import('./src/components/MonitorVideoBoxFull.vue')['default']
    MonitorVideoBoxHeader: typeof import('./src/components/MonitorVideoBoxHeader.vue')['default']
    MonitorVideoBoxMiddle: typeof import('./src/components/MonitorVideoBoxMiddle.vue')['default']
    MonitorVideoBoxSmall: typeof import('./src/components/MonitorVideoBoxSmall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
